#! /bin/bash

BAZEL_EXE=bazel

OUT=${1:-Envoy.includes}
OUT_ABS=$(dirname $(realpath ${OUT}))

# Find current bazel-cache
BZOUTDIR="$(${BAZEL_EXE} info output_base)"
BZOUTDIR_REL=$(abs2rel "${BZOUTDIR}" "${OUT_ABS}" )

cat >${OUT} <<EOF
contrib/common/sqlutils/source
contrib/cryptomb/private_key_providers/source
contrib/cryptomb/private_key_providers/test
contrib/kafka/filters/network/source
contrib/kafka/filters/network/source/broker
contrib/kafka/filters/network/source/mesh
contrib/kafka/filters/network/source/mesh/command_handlers
contrib/kafka/filters/network/test
contrib/kafka/filters/network/test/mesh
contrib/mysql_proxy/filters/network/source
contrib/mysql_proxy/filters/network/test
contrib/postgres_proxy/filters/network/source
contrib/postgres_proxy/filters/network/test
contrib/rocketmq_proxy/filters/network/source
contrib/rocketmq_proxy/filters/network/source/router
contrib/rocketmq_proxy/filters/network/test
contrib/sip_proxy/filters/network/source
contrib/sip_proxy/filters/network/source/filters
contrib/sip_proxy/filters/network/source/router
contrib/sip_proxy/filters/network/source/tra
contrib/sip_proxy/filters/network/test
contrib/squash/filters/http/source
contrib/sxg/filters/http/source
contrib/vcl/source
envoy/access_log
envoy/api
envoy/buffer
envoy/common
envoy/common/crypto
envoy/compression/compressor
envoy/compression/decompressor
envoy/config
envoy/event
envoy/filesystem
envoy/filter
envoy/formatter
envoy/grpc
envoy/http
envoy/init
envoy/json
envoy/local_info
envoy/matcher
envoy/network
envoy/protobuf
envoy/ratelimit
envoy/rds
envoy/registry
envoy/router
envoy/runtime
envoy/secret
envoy/server
envoy/server/overload
envoy/singleton
envoy/ssl
envoy/ssl/private_key
envoy/stats
envoy/stream_info
envoy/tcp
envoy/thread
envoy/thread_local
envoy/tracing
envoy/udp
envoy/upstream
source/common/access_log
source/common/api
source/common/api/posix
source/common/api/win32
source/common/buffer
source/common/common
source/common/common/android
source/common/common/posix
source/common/common/standard
source/common/common/win32
source/common/config
source/common/config/xds_mux
source/common/conn_pool
source/common/crypto
source/common/event
source/common/event/posix
source/common/event/win32
source/common/filesystem
source/common/filesystem/inotify
source/common/filesystem/kqueue
source/common/filesystem/posix
source/common/filesystem/win32
source/common/filter
source/common/formatter
source/common/grpc
source/common/html
source/common/http
source/common/http/http1
source/common/http/http2
source/common/http/http3
source/common/http/match_wrapper
source/common/http/matching
source/common/init
source/common/json
source/common/local_info
source/common/local_reply
source/common/matcher
source/common/memory
source/common/network
source/common/network/dns_resolver
source/common/network/matching
source/common/profiler
source/common/protobuf
source/common/quic
source/common/quic/platform
source/common/rds
source/common/router
source/common/runtime
source/common/secret
source/common/shared_pool
source/common/signal
source/common/singleton
source/common/ssl
source/common/stats
source/common/stream_info
source/common/tcp
source/common/tcp_proxy
source/common/thread
source/common/thread_local
source/common/tracing
source/common/upstream
source/common/version
source/common/watchdog
source/exe
source/exe/win32
source/extensions/access_loggers/common
source/extensions/access_loggers/file
source/extensions/access_loggers/filters/cel
source/extensions/access_loggers/grpc
source/extensions/access_loggers/open_telemetry
source/extensions/access_loggers/stream
source/extensions/access_loggers/wasm
source/extensions/bootstrap/wasm
source/extensions/clusters/aggregate
source/extensions/clusters/dynamic_forward_proxy
source/extensions/clusters/redis
source/extensions/common/aws
source/extensions/common/dynamic_forward_proxy
source/extensions/common/matcher
source/extensions/common/proxy_protocol
source/extensions/common/redis
source/extensions/common/tap
source/extensions/common/wasm
source/extensions/common/wasm/ext
source/extensions/compression/brotli/common
source/extensions/compression/brotli/compressor
source/extensions/compression/brotli/decompressor
source/extensions/compression/common/compressor
source/extensions/compression/common/decompressor
source/extensions/compression/gzip/common
source/extensions/compression/gzip/compressor
source/extensions/compression/gzip/decompressor
source/extensions/config/validators/minimum_clusters
source/extensions/filters/common/expr
source/extensions/filters/common/ext_authz
source/extensions/filters/common/fault
source/extensions/filters/common/local_ratelimit
source/extensions/filters/common/lua
source/extensions/filters/common/mutation_rules
source/extensions/filters/common/original_src
source/extensions/filters/common/ratelimit
source/extensions/filters/common/rbac
source/extensions/filters/common/rbac/matchers
source/extensions/filters/http
source/extensions/filters/http/adaptive_concurrency
source/extensions/filters/http/adaptive_concurrency/controller
source/extensions/filters/http/admission_control
source/extensions/filters/http/admission_control/evaluators
source/extensions/filters/http/alternate_protocols_cache
source/extensions/filters/http/aws_lambda
source/extensions/filters/http/aws_request_signing
source/extensions/filters/http/bandwidth_limit
source/extensions/filters/http/buffer
source/extensions/filters/http/cache
source/extensions/filters/http/cache/simple_http_cache
source/extensions/filters/http/cdn_loop
source/extensions/filters/http/common
source/extensions/filters/http/composite
source/extensions/filters/http/compressor
source/extensions/filters/http/cors
source/extensions/filters/http/csrf
source/extensions/filters/http/decompressor
source/extensions/filters/http/dynamic_forward_proxy
source/extensions/filters/http/dynamo
source/extensions/filters/http/ext_authz
source/extensions/filters/http/ext_proc
source/extensions/filters/http/fault
source/extensions/filters/http/grpc_http1_bridge
source/extensions/filters/http/grpc_http1_reverse_bridge
source/extensions/filters/http/grpc_json_transcoder
source/extensions/filters/http/grpc_stats
source/extensions/filters/http/grpc_web
source/extensions/filters/http/header_to_metadata
source/extensions/filters/http/health_check
source/extensions/filters/http/ip_tagging
source/extensions/filters/http/jwt_authn
source/extensions/filters/http/kill_request
source/extensions/filters/http/local_ratelimit
source/extensions/filters/http/lua
source/extensions/filters/http/oauth2
source/extensions/filters/http/on_demand
source/extensions/filters/http/original_src
source/extensions/filters/http/ratelimit
source/extensions/filters/http/rbac
source/extensions/filters/http/router
source/extensions/filters/http/set_metadata
source/extensions/filters/http/stateful_session
source/extensions/filters/http/tap
source/extensions/filters/http/wasm
source/extensions/filters/listener/http_inspector
source/extensions/filters/listener/original_dst
source/extensions/filters/listener/original_src
source/extensions/filters/listener/proxy_protocol
source/extensions/filters/listener/tls_inspector
source/extensions/filters/network
source/extensions/filters/network/client_ssl_auth
source/extensions/filters/network/common
source/extensions/filters/network/common/redis
source/extensions/filters/network/connection_limit
source/extensions/filters/network/direct_response
source/extensions/filters/network/dubbo_proxy
source/extensions/filters/network/dubbo_proxy/filters
source/extensions/filters/network/dubbo_proxy/router
source/extensions/filters/network/echo
source/extensions/filters/network/ext_authz
source/extensions/filters/network/http_connection_manager
source/extensions/filters/network/local_ratelimit
source/extensions/filters/network/mongo_proxy
source/extensions/filters/network/ratelimit
source/extensions/filters/network/rbac
source/extensions/filters/network/redis_proxy
source/extensions/filters/network/sni_cluster
source/extensions/filters/network/sni_dynamic_forward_proxy
source/extensions/filters/network/tcp_proxy
source/extensions/filters/network/thrift_proxy
source/extensions/filters/network/thrift_proxy/filters
source/extensions/filters/network/thrift_proxy/filters/header_to_metadata
source/extensions/filters/network/thrift_proxy/filters/ratelimit
source/extensions/filters/network/thrift_proxy/router
source/extensions/filters/network/wasm
source/extensions/filters/network/zookeeper_proxy
source/extensions/filters/udp/dns_filter
source/extensions/filters/udp/udp_proxy
source/extensions/formatter/metadata
source/extensions/formatter/req_without_query
source/extensions/grpc_credentials/aws_iam
source/extensions/grpc_credentials/example
source/extensions/grpc_credentials/file_based_metadata
source/extensions/health_checkers/redis
source/extensions/http/header_formatters/preserve_case
source/extensions/http/original_ip_detection/custom_header
source/extensions/http/original_ip_detection/xff
source/extensions/http/stateful_session/cookie
source/extensions/internal_redirect/allow_listed_routes
source/extensions/internal_redirect/previous_routes
source/extensions/internal_redirect/safe_cross_scheme
source/extensions/io_socket/user_space
source/extensions/key_value/file_based
source/extensions/matching/common_inputs/environment_variable
source/extensions/matching/input_matchers/consistent_hashing
source/extensions/matching/input_matchers/ip
source/extensions/network/dns_resolver/apple
source/extensions/network/dns_resolver/cares
source/extensions/quic/crypto_stream
source/extensions/quic/proof_source
source/extensions/rate_limit_descriptors/expr
source/extensions/request_id/uuid
source/extensions/resource_monitors/common
source/extensions/resource_monitors/fixed_heap
source/extensions/resource_monitors/injected_resource
source/extensions/retry/host/omit_canary_hosts
source/extensions/retry/host/omit_host_metadata
source/extensions/retry/host/previous_hosts
source/extensions/retry/priority/previous_priorities
source/extensions/stat_sinks/common/statsd
source/extensions/stat_sinks/dog_statsd
source/extensions/stat_sinks/graphite_statsd
source/extensions/stat_sinks/hystrix
source/extensions/stat_sinks/metrics_service
source/extensions/stat_sinks/statsd
source/extensions/stat_sinks/wasm
source/extensions/tracers/common
source/extensions/tracers/common/ot
source/extensions/tracers/datadog
source/extensions/tracers/dynamic_ot
source/extensions/tracers/lightstep
source/extensions/tracers/opencensus
source/extensions/tracers/skywalking
source/extensions/tracers/xray
source/extensions/tracers/zipkin
source/extensions/transport_sockets/alts
source/extensions/transport_sockets/common
source/extensions/transport_sockets/proxy_protocol
source/extensions/transport_sockets/raw_buffer
source/extensions/transport_sockets/starttls
source/extensions/transport_sockets/tap
source/extensions/transport_sockets/tcp_stats
source/extensions/transport_sockets/tls
source/extensions/transport_sockets/tls/cert_validator
source/extensions/transport_sockets/tls/cert_validator/spiffe
source/extensions/transport_sockets/tls/ocsp
source/extensions/transport_sockets/tls/private_key
source/extensions/upstreams/http
source/extensions/upstreams/http/generic
source/extensions/upstreams/http/http
source/extensions/upstreams/http/tcp
source/extensions/upstreams/tcp/generic
source/extensions/watchdog/profile_action
source/server
source/server/admin
source/server/config_validation
test
test/benchmark
test/common/buffer
test/common/config
test/common/formatter
test/common/grpc
test/common/http
test/common/http/http2
test/common/matcher
test/common/network
test/common/quic
test/common/quic/platform
test/common/router
test/common/stats
test/common/stream_info
test/common/tcp_proxy
test/common/upstream
test/config
test/config/integration/certs
test/config_test
test/extensions/access_loggers/stream
test/extensions/clusters/redis
test/extensions/common/aws
test/extensions/common/dynamic_forward_proxy
test/extensions/common/redis
test/extensions/common/tap
test/extensions/common/wasm
test/extensions/filters/common/ext_authz
test/extensions/filters/common/lua
test/extensions/filters/common/ratelimit
test/extensions/filters/common/rbac
test/extensions/filters/http/adaptive_concurrency
test/extensions/filters/http/cache
test/extensions/filters/http/common
test/extensions/filters/http/common/fuzz
test/extensions/filters/http/compressor
test/extensions/filters/http/ext_proc
test/extensions/filters/http/fault
test/extensions/filters/http/jwt_authn
test/extensions/filters/http/rbac
test/extensions/filters/http/tap
test/extensions/filters/listener/common/fuzz
test/extensions/filters/listener/proxy_protocol
test/extensions/filters/listener/tls_inspector
test/extensions/filters/network/common/fuzz
test/extensions/filters/network/common/fuzz/utils
test/extensions/filters/network/common/redis
test/extensions/filters/network/dubbo_proxy
test/extensions/filters/network/http_connection_manager
test/extensions/filters/network/redis_proxy
test/extensions/filters/network/thrift_proxy
test/extensions/filters/udp/dns_filter
test/extensions/tracers/skywalking
test/extensions/transport_sockets/tls
test/extensions/transport_sockets/tls/cert_validator
test/extensions/transport_sockets/tls/cert_validator/spiffe
test/extensions/transport_sockets/tls/integration
test/extensions/transport_sockets/tls/test_data
test/fuzz
test/integration
test/integration/clusters
test/integration/filters
test/integration/load_balancers
test/integration/upstreams
test/mocks
test/mocks/access_log
test/mocks/api
test/mocks/buffer
test/mocks/compression/compressor
test/mocks/compression/decompressor
test/mocks/config
test/mocks/event
test/mocks/filesystem
test/mocks/grpc
test/mocks/http
test/mocks/init
test/mocks/local_info
test/mocks/local_reply
test/mocks/matcher
test/mocks/network
test/mocks/protobuf
test/mocks/ratelimit
test/mocks/router
test/mocks/runtime
test/mocks/secret
test/mocks/server
test/mocks/ssl
test/mocks/stats
test/mocks/stream_info
test/mocks/tcp
test/mocks/thread_local
test/mocks/tracing
test/mocks/upstream
test/server
test/server/admin
test/server/config_validation
test/test_common
test/tools/router_check
test/tools/schema_validator
.
bazel-bin
EOF

for dir in $(find ${BZOUTDIR_REL} -name include -print) ; do
	echo >>"${OUT}" "${dir}"
done
echo >>"${OUT}" "${BZOUTDIR_REL}/external/com_envoyproxy_protoc_gen_validate"

# Add a blank line at the end, or the last include-dir is not taken into account
echo >>"${OUT}"

